In [1]:
class Kitap:
    def __init__(self, atau, avtory):
        self.atau = atau        
        self.avtory = avtory    

    def kitap_turaly_malimet(self):
        print(f"Кітап: {self.atau}, Авторы: {self.avtory}")


# Нысан (объект) жасау
kitap1 = Kitap("Абай жолы", "Мұхтар Әуезов")

# Әдісті шақыру
kitap1.kitap_turaly_malimet()

Кітап: Абай жолы, Авторы: Мұхтар Әуезов


In [2]:
import numpy as np

arr_a = np.arange(1, 10)

arr_b = np.arange(1, 10).reshape(3, 3)

print("arr_a:", arr_a)
print("arr_a shape:", arr_a.shape)
print("arr_a dtype:", arr_a.dtype)

print("\narr_b:\n", arr_b)
print("arr_b shape:", arr_b.shape)
print("arr_b dtype:", arr_b.dtype)

arr_a: [1 2 3 4 5 6 7 8 9]
arr_a shape: (9,)
arr_a dtype: int64

arr_b:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr_b shape: (3, 3)
arr_b dtype: int64


In [3]:
import numpy as np
vec1 = np.random.randint(1, 11, size=5)
vec2 = np.random.randint(1, 11, size=5)

print("vec1:", vec1)
print("vec2:", vec2)
sum_vec = vec1 + vec2
print("\nҚосу нәтижесі:", sum_vec)

square_vec1 = vec1 ** 2
print("vec1 квадраттары:", square_vec1)

mean_vec1 = vec1.mean()
print("vec1 орташа мәні:", mean_vec1)
max_vec1 = vec1.max()
print("vec1 ең үлкен мәні:", max_vec1)

vec1: [ 3  3  2 10  6]
vec2: [10 10  2  8  8]

Қосу нәтижесі: [13 13  4 18 14]
vec1 квадраттары: [  9   9   4 100  36]
vec1 орташа мәні: 4.8
vec1 ең үлкен мәні: 10
